services:
  php:
    build: ./.docker/php
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony

  nginx:
    build: ./.docker/nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

 # db:
 #   image: mysql:8.0.33
 #   environment:
 #     MYSQL_ROOT_PASSWORD: secret
 #     MYSQL_DATABASE: symfony
 #     MYSQL_USER: symfony
 #     MYSQL_PASSWORD: secret
 #   networks:
 #     - symfony

networks:
  symfony: